import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddressButton from "@/components/profile";
import {NextUIProvider} from "@nextui-org/react";
import { Logo } from "@/components/logo";
import Navigator from "@/components/navigator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextUIProvider>
        <Navigator />
        {children}
      </NextUIProvider>
      </body>
      
    </html>
  );
}
