import type { Metadata } from "next";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import Navigator from "@/components/navigator";

import localFont from 'next/font/local'
 
// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './JxTabeDEMO-Regular.ttf',
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={myFont.className}>
      <body>
      <NextUIProvider>
        <Navigator />
        {children}
      </NextUIProvider>
      </body>
      
    </html>
  );
}
